### ISSUE TITLE
Multiple Domains with Passive and Active 

### ISSUE THREAD

**Issue by Thurnun** [leebaird/discover#135]
Title mostly says it,

Is there built-in function within discover recon to run the Passive/Active against a list of domains?

By the way great job on this project, I use it regularly.

Thank you for your time,

**Comment by leebaird** [comment]
On behalf of Jason, Jay, and myself thanks!
We are glad that you are using and enjoying our project. This is the first time this request has came up. I don't think it is likely to happen, because there are too many things that could possible go wrong with a single scan. Especially since we are chaining together 43 tools now and 52 recon-ng modules in passive mode. But we always welcome suggestions.

Lee
