### ISSUE TITLE
Active Recon script gives error. 

### ISSUE THREAD

**Issue by xtreme33** [leebaird/discover#144]
When I run ./discover.sh and go to RECON/Active (2), I get the following error:

RECON

1.  Passive
2.  Active
3.  Import names into an existing recon-ng workspace
4.  Previous menu

Choice: 2
dnsrecon
     DNS Records          (1/9)
usage: dnsrecon.py [-h] [-d DOMAIN] [-n NS_SERVER] [-r RANGE] [-D DICTIONARY]
                   [-f] [-t TYPE] [-a] [-s] [-g] [-b] [-k] [-w] [-z]
                   [--threads THREADS] [--lifetime LIFETIME] [--tcp] [--db DB]
                   [-x XML] [-c CSV] [-j JSON] [--iw]
                   [--disable_check_recursion] [--disable_check_bindversion]
                   [-v]
dnsrecon.py: error: argument -d/--domain: expected one argument
cp: cannot create regular file '/root/data//data/records.htm': No such file or directory
/opt/discover/active.sh: line 17: /root/data//data/records.htm: No such file or directory
/opt/discover/active.sh: line 18: /root/data//data/records.htm: No such file or directory
     Sub-domains          (2/9)
usage: dnsrecon.py [-h] [-d DOMAIN] [-n NS_SERVER] [-r RANGE] [-D DICTIONARY]
                   [-f] [-t TYPE] [-a] [-s] [-g] [-b] [-k] [-w] [-z]
                   [--threads THREADS] [--lifetime LIFETIME] [--tcp] [--db DB]
                   [-x XML] [-c CSV] [-j JSON] [--iw]
                   [--disable_check_recursion] [--disable_check_bindversion]
                   [-v]
dnsrecon.py: error: argument -d/--domain: expected one argument

**Comment by L1ghtn1ng** [comment]
I have just pushed a fix for this initial problem but there is more issues with this script that needs fixing

**Comment by xtreme33** [comment]
No problem, I did some some changes but just wanted to let you know just
in case. Thanks.

**Comment by leebaird** [comment]
There are 3 different bugs I'm seeing:

1. Script hangs in the beginning like previously reported. This is due to something with dnsrecon.

2. I'm testing this on a domain that I haven't previously ran a passive scan against. So we need to check for that. If that scan has NOT ran, we need to copy over the entire report folder.

3. Missing pages because no passive scan was ran.
[recon-ng][acme.com] > exit
/opt/discover/active.sh: line 202: /root/data/acme.com/data/active-recon.htm: No such file or directory
/opt/discover/active.sh: line 203: /root/data/acme.com/data/active-recon.htm: No such file or directory
/opt/discover/active.sh: line 204: /root/data/acme.com/data/traceroute.htm: No such file or directory
/opt/discover/active.sh: line 205: /root/data/acme.com/data/traceroute.htm: No such file or directory
/opt/discover/active.sh: line 206: /root/data/acme.com/data/waf.htm: No such file or directory
/opt/discover/active.sh: line 207: /root/data/acme.com/data/waf.htm: No such file or directory
/opt/discover/active.sh: line 208: /root/data/ace.com/data/whatweb.htm: No such file or directory
/opt/discover/active.sh: line 209: /root/data/acme.com/data/whatweb.htm: No such file or directory
/opt/discover/active.sh: line 210: /root/data/acme.com/data/zonetransfer.htm: No such file or directory
/opt/discover/active.sh: line 211: /root/data/acme.com/data/zonetransfer.htm: No such file or directory

**Comment by leebaird** [comment]
fixed
