### ISSUE TITLE
Recon options not working

### ISSUE THREAD

**Issue by Matthoare** [leebaird/discover#184]
Recon not working, only options working are 4, 5, 6 and 7, I am using the latest VM version of Kali (2022.1-vmware-amd64).

I have installed this in the recommended location /opt/discover

To make sure there was no other software/installed programs causing this issue I spun up a new VM so it was a totally fresh version of Kali and the issue persisted.

I have also removed this and reinstalled as this worked for others

**Comment by leebaird** [comment]
Matt,

What is not working? 
Are you seeing any errors?
I can't reproduce this.

**Comment by Matthoare** [comment]
Hi Lee,
Thank for the response and I appologise for the lack of information.
So I have installed in using the documentation, however when i try to run most of the options it does nothing.
For example I want to run domain within ght recon section I press 1, Press enter and nothing happends, the number 1 dissapears and nothing else happends.

I have tried to do a fresh install using an iso rather than a VM clone, however I am getting the same results.

**Comment by L1ghtn1ng** [comment]
Hi Matt,

Have you ran update.sh? Is there any errors?

Also what version of kali are you using?

On 7 Apr 2022, at 18:38, Matthoare ***@***.***> wrote:

﻿

Hi Lee,
Thank for the response and I appologise for the lack of information.
So I have installed in using the documentation, however when i try to run most of the options it does nothing.
For example I want to run domain within ght recon section I press 1, Press enter and nothing happends, the number 1 dissapears and nothing else happends.

I have tried to do a fresh install using an iso rather than a VM clone, however I am getting the same results.

**Comment by Matthoare** [comment]
Hi,

Yes I ran update.sh as soon as it was installed.

In regards to versions I ran both the latest versions (ISO 2022.1, VM 2022.1)

I hope this information helps

**Comment by leebaird** [comment]
Matt,

If you could provide us your email, we can add you to our Slack channel where we can better assist.

**Comment by Matthoare** [comment]
Hi Lee, 

my email: matt_soton@hitmail.com

**Comment by jrod1481** [comment]
Hello, I am having a similiar issue with the person above. The recon modules, for instance Domain does not work. If I try to type in "1" for Domain, essentailly nothing happens. Is there a work around? using latest version of kali.

**Comment by leebaird** [comment]
I just spun up a new 64-bit VMware image, patched the OS, cloned the repo, and ran Discover with no issues.
I suggest using one of the pre-build VM located here: https://www.kali.org/get-kali/#kali-virtual-machines
Be sure to verify the SHA256sum. This is super important.

**Comment by HoaithiPrl** [comment]
Hi Lee,

I have the same problem, can you add me to Slack too
My email: phunghoaithi137@gmail.com

**Comment by leebaird** [comment]
Invite sent.
