### ISSUE TITLE
Script is not creating folders

### ISSUE THREAD

**Issue by natv** [leebaird/discover#35]
Hello,

Running into an issue running this on Kali 2.x

Here's an example:

Choice: 1

=====================================================================================

Usage

Company: Target
Domain:  target.com

=====================================================================================

Company: Walmart
Domain:  walmart.com
cp: target ‘/root/data/walmart.com’ is not a directory
sed: can't read /root/data/walmart.com/index.htm: No such file or directory
mv: cannot move ‘tmp’ to ‘/root/data/walmart.com/index.htm’: No such file or directory

=====================================================================================

dnsrecon                  (1/26)

goofile                   (2/26)

goog-mail                 (3/26)
./discover.sh: line 210: /opt/discover: Is a directory

goohost
     IP                   (4/26)
./discover.sh: line 222: /opt/discover: Is a directory
     Email                (5/26)
./discover.sh: line 224: /opt/discover: Is a directory
cat: report-*: No such file or directory
rm: cannot remove ‘*-walmart.com.txt’: No such file or directory

theHarvester
     Baidu                (6/26)
     Bing                 (7/26)

Please advise how to fix this.

Thanks

**Comment by jayw0k** [comment]
You likely have discover.sh in an additional path (trash?), which is being grabbed instead of /opt/discover/

Do the following:
`locate discover.sh`
Remove discover.sh from all paths except /opt/discover/
If you need a separate copy, it will need to be renamed (ex. discover-copy.sh) to not conflict with Discover validating its path
`updatedb`

Run Discover again & report back on your results

**Comment by natv** [comment]
Thanks jayw0k that worked, I just needed to also do an 'updatedb' after renaming the other discover.sh scripts and it's running now  :)
